---
windows:
  hosts:
    10.13.37.10:
    10.13.37.100:
    10.13.37.150:
  vars:
    # Variables de conexión para todo el grupo [windows]
    ansible_connection: winrm
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_winrm_transport: ntlm
    # Especificamos que la conexión es por HTTP (no cifrado)
    ansible_winrm_scheme: http
    # Le decimos a Ansible que nuestro método es inseguro pero está bien
    ansible_winrm_server_cert_validation: ignore
    # y dado que va a ir por el puerto 5986, le indico que vaya al 5985...
    ansible_port: 5985
    domain_name: adlab.local
    domain_safe_mode_password: P@ssw0rd123! 
  children:
    dc:
      hosts:
        10.13.37.10:
    winserv2019:
      hosts:
        10.13.37.100:
    win10:
      hosts:
        10.13.37.150:
